import type { LoaderFunctionArgs } from "@remix-run/node";
import { Form, redirect, useLoaderData } from "@remix-run/react";
import {
    BlockStack,
    Button,
    Card,
    Divider,
    FormLayout,
    Grid,
    InlineStack,
    Page,
    AppProvider as PolarisAppProvider,
    Text,
    TextField,
} from "@shopify/polaris";
import polarisStyles from "@shopify/polaris/build/esm/styles.css?url";
import polarisTranslations from "@shopify/polaris/locales/en.json";
import { useState } from "react";
import { login } from "../../shopify.server";

export const links = () => [{ rel: "stylesheet", href: polarisStyles }];

export const loader = async ({ request }: LoaderFunctionArgs) => {
    const url = new URL(request.url);

    if (url.searchParams.get("shop")) {
        throw redirect(`/app?${url.searchParams.toString()}`);
    }

    return Response.json({ showForm: Boolean(login), polarisTranslations });
};

export default function App() {
    const { polarisTranslations } = useLoaderData<typeof loader>();

    return (
        <PolarisAppProvider i18n={polarisTranslations}>
            <Page>
                <Landing />
            </Page>
        </PolarisAppProvider>
    );
}

function Landing() {
    const { showForm } = useLoaderData<typeof loader>();

    return (
        <BlockStack gap="800" inlineAlign="center">
            <img src="https://frak.id/assets/logo-frak.png" alt="Logo" />
            <Text variant="heading2xl" as="h1" alignment="center">
                Scale Authenticity with Word-of-Mouth
            </Text>

            <Divider />

            <Text variant="headingLg" as="h4" alignment="center">
                Reward your customers for genuine recommendations, cut
                acquisition costs, and foster lasting loyalty.
            </Text>

            <Divider />

            <Grid columns={{ sm: 2, md: 4, lg: 4 }}>
                <Grid.Cell>
                    <Card>
                        <strong>Cash Rewards</strong>. Automatically and
                        instantly reward actions generated by sharing.
                    </Card>
                </Grid.Cell>
                <Grid.Cell>
                    <Card>
                        <strong>Return On Investment</strong>. Pay only for
                        results—your budget goes straight to your customers, not
                        social networks!
                    </Card>
                </Grid.Cell>
                <Grid.Cell>
                    <Card>
                        <strong>Lower Acquisition Costs</strong>. Reduce
                        acquisition costs up to 8.3 times compared to
                        traditional ads.
                    </Card>
                </Grid.Cell>
                <Grid.Cell>
                    <Card>
                        <strong>Increase Brand Loyalty</strong>. Create
                        authentic connections and boost loyalty by valuing every
                        customer.
                    </Card>
                </Grid.Cell>
            </Grid>

            {showForm && <ShopForm />}
        </BlockStack>
    );
}

function ShopForm() {
    const [shop, setShop] = useState("");

    return (
        <BlockStack gap="400">
            <Text variant="headingMd" as="h3">
                Connect your store to start using Frak
            </Text>

            <Form method="post" action="/auth/login">
                <FormLayout>
                    <TextField
                        type="text"
                        name="shop"
                        label="Shop domain"
                        helpText="e.g: my-shop-domain.myshopify.com"
                        value={shop}
                        onChange={setShop}
                        autoComplete="on"
                    />
                    <InlineStack align="end">
                        <Button submit>Connect</Button>
                    </InlineStack>
                </FormLayout>
            </Form>
        </BlockStack>
    );
}
