# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87da8338f40c95301b4881ca4bfb23db"
name = "Frak"
handle = "frak"
application_url = "https://extension-shop.frak.id"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app_purchases_one_time/update", "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_pixels,read_products,read_themes,write_pixels"

[auth]
redirect_urls = [
  "https://extension-shop.frak.id/auth/callback",
  "https://extension-shop.frak.id/auth/shopify/callback",
  "https://extension-shop.frak.id/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
