# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a65623a5ceb9e6dc7147271eb7bb9f1"
application_url = "https://extension-shop.frak.id"
embedded = true
name = "Frak Custom"
handle = "frak-custom"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-frak.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_pixels,read_products,read_themes,write_pixels"

[auth]
redirect_urls = [
  "https://extension-shop.frak.id/auth/callback",
  "https://extension-shop.frak.id/auth/shopify/callback",
  "https://extension-shop.frak.id/api/auth/callback"
]

[pos]
embedded = false
