/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MasterVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "POSTGRES_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTGRES_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_API_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Shopify": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
